import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>1</li>
        <li className={`${styles.flex2}`}>2</li>
        <li>3</li>
        <li>4</li>
        <li className={`${styles.flex2}`}>5</li>
        <li>6</li>
      </ul>
    </div>
  )
}
